# See https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  misspell:
    locale: US
  unused:
    check-exported: false
  unparam:
    check-exported: true

linters:
  enable-all: true
  disable:
    - copyloopvar
    - depguard
    - dupl # some code duplication is traded for 1 alloc
    - dupword
    - errname
    - exportloopref
    - execinquery
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gomnd
    - intrange
    - lll
    - mnd
    - nonamedreturns
    - paralleltest
    - tagalign
    - tagliatelle
    - testableexamples
    - varnamelen
    - wrapcheck

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - dupl
        - err113
        - fatcontext
        - funlen
        - goconst
        - goerr113
        - gomnd
        - mnd
        - noctx
        - structcheck
        - unparam
        - unused
      path: "_test.go"
    - linters:
        - errcheck # Error checking omitted for brevity.
        - gosec
      path: "example_"
